addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "1.2.1")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "0.6.3")
addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")
